"""Generate the pinned offline Pal hunger metadata used by Ticket 04."""

from __future__ import annotations

import hashlib
import json
import urllib.request
from pathlib import Path
from typing import Any

SOURCE_REPOSITORY = "https://github.com/deafdudecomputers/PalworldSaveTools"
SOURCE_REVISION = "18b9554168ecf684c5f1e1e4d8e583083b942eb9"
SOURCE_SHA256 = "83373a0e6dab7f3feac88a08928356b955e07804e0da94b2d452e641ab2609f2"
SOURCE_URL = (
    f"https://raw.githubusercontent.com/deafdudecomputers/PalworldSaveTools/"
    f"{SOURCE_REVISION}/resources/game_data/characters.json"
)
OUTPUT = Path(__file__).resolve().parents[1] / "palserver_console/world/pal_care_species.py"


def main() -> None:
    source = urllib.request.urlopen(SOURCE_URL, timeout=30).read()  # noqa: S310
    digest = hashlib.sha256(source).hexdigest()
    if digest != SOURCE_SHA256:
        raise ValueError(f"Unexpected characters.json SHA-256: {digest}")
    payload: dict[str, Any] = json.loads(source)
    values = {
        str(pal["asset"]): float(pal["stats"]["max_full_stomach"])
        for pal in payload["pals"]
        if float(pal["stats"].get("max_full_stomach") or 0) > 0
    }
    rows = "\n".join(f"    {key!r}: {values[key]!r}," for key in sorted(values))
    OUTPUT.write_text(
        f'''"""Generated offline Pal care metadata; do not edit by hand.

Source: {SOURCE_REPOSITORY}
Revision: {SOURCE_REVISION}
Input SHA-256: {SOURCE_SHA256}
Generated by: backend/tools/generate_pal_care_species.py
"""

from __future__ import annotations

PAL_MAX_FULL_STOMACH: dict[str, float] = {{
{rows}
}}
_PAL_MAX_FULL_STOMACH_CASEFOLD = {{
    key.casefold(): value for key, value in PAL_MAX_FULL_STOMACH.items()
}}


def max_full_stomach(character_id: str) -> float | None:
    return PAL_MAX_FULL_STOMACH.get(character_id) or _PAL_MAX_FULL_STOMACH_CASEFOLD.get(
        character_id.casefold()
    )
''',
        encoding="utf-8",
    )
    print(f"Generated {len(values)} Pal hunger metadata rows.")


if __name__ == "__main__":
    main()
